apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1 # Number of replicas to create
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/kodekloud-gcp-training/test-gcpdevops:latest
        ports:
        - containerPort: 5000 # Port number to expose
        env:
          - name: PORT
            value: "5000"
