apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1 # Number of replicas to create
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/fourth-archive-369312/gcpdevops:latest
        ports:
        - containerPort: 5000 # Port number to expose
        env:
          - name: PORT
            value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-prod
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

